name: Build Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
  test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm install
        working-directory: ./web
      - name: Run build
        run: npm run build
        working-directory: ./web
